version: '3.8'
services:
  user-service:
    build: ./backend/user-service
    ports:
      - "8081:8081"
  product-service:
    build: ./backend/product-service
    ports:
      - "8082:8082"
  order-service:
    build: ./backend/order-service
    ports:
      - "8083:8083"
  payment-service:
    build: ./backend/payment-service
    ports:
      - "8084:8084"
  recommendation-service:
    build: ./backend/recommendation-service
    ports:
      - "8085:8085"
